import type { AppData, PriceCatalogItem } from '../types';

export const STORAGE_KEY = 'homelife-data-v2';
const LEGACY_KEYS = ['homelife-data-v1', 'homelife-data', 'homelifeData'];
const CATALOG_RESTORE_FLAG = 'homelife-catalog-restored-20260615-0010';

const DEFAULT_PRICE_CATALOG: PriceCatalogItem[] = [
  {
    id: "seed-wm-0001",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Milk",
    brand: "Great Value",
    size: "1 gallon",
    category: "Dairy",
    price: 3.32,
    unit: "gal",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0001",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Milk",
    brand: "Store Brand",
    size: "1 gallon",
    category: "Dairy",
    price: 3.48,
    unit: "gal",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0002",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Eggs",
    brand: "Great Value",
    size: "18 count",
    category: "Dairy",
    price: 5.74,
    unit: "ct",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0002",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Eggs",
    brand: "Store Brand",
    size: "18 count",
    category: "Dairy",
    price: 5.99,
    unit: "ct",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0003",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Butter",
    brand: "Great Value",
    size: "1 lb",
    category: "Dairy",
    price: 4.48,
    unit: "lb",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0003",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Butter",
    brand: "Store Brand",
    size: "1 lb",
    category: "Dairy",
    price: 4.79,
    unit: "lb",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0004",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Shredded Cheddar Cheese",
    brand: "Great Value",
    size: "16 oz",
    category: "Dairy",
    price: 3.98,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0004",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Shredded Cheddar Cheese",
    brand: "Store Brand",
    size: "16 oz",
    category: "Dairy",
    price: 4.29,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0005",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Sour Cream",
    brand: "Great Value",
    size: "16 oz",
    category: "Dairy",
    price: 1.98,
    unit: "tub",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0005",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Sour Cream",
    brand: "Store Brand",
    size: "16 oz",
    category: "Dairy",
    price: 2.29,
    unit: "tub",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0006",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Greek Yogurt",
    brand: "Great Value",
    size: "32 oz",
    category: "Dairy",
    price: 3.84,
    unit: "tub",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0006",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Greek Yogurt",
    brand: "Store Brand",
    size: "32 oz",
    category: "Dairy",
    price: 4.19,
    unit: "tub",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0007",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Chicken Breast",
    brand: "Freshness Guaranteed",
    size: "per package",
    category: "Meats",
    price: 11.92,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0007",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Chicken Breast",
    brand: "Freshness Guaranteed",
    size: "per package",
    category: "Meats",
    price: 12.49,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0008",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Ground Beef 80/20",
    brand: "Fresh Ground",
    size: "1 lb",
    category: "Meats",
    price: 5.48,
    unit: "lb",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0008",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Ground Beef 80/20",
    brand: "Fresh Ground",
    size: "1 lb",
    category: "Meats",
    price: 5.89,
    unit: "lb",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0009",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Pork Chops",
    brand: "Fresh Pork",
    size: "1 lb",
    category: "Meats",
    price: 3.98,
    unit: "lb",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0009",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Pork Chops",
    brand: "Fresh Pork",
    size: "1 lb",
    category: "Meats",
    price: 4.29,
    unit: "lb",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0010",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Bacon",
    brand: "Great Value",
    size: "12 oz",
    category: "Meats",
    price: 4.48,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0010",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Bacon",
    brand: "Store Brand",
    size: "12 oz",
    category: "Meats",
    price: 4.79,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0011",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Sliced Turkey",
    brand: "Oscar Mayer",
    size: "16 oz",
    category: "Meats",
    price: 5.98,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0011",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Sliced Turkey",
    brand: "Oscar Mayer",
    size: "16 oz",
    category: "Meats",
    price: 6.49,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0012",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Frozen Chicken Nuggets",
    brand: "Great Value",
    size: "32 oz",
    category: "Frozen Foods",
    price: 6.98,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0012",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Frozen Chicken Nuggets",
    brand: "Store Brand",
    size: "32 oz",
    category: "Frozen Foods",
    price: 7.49,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0013",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Frozen Pizza",
    brand: "Great Value",
    size: "rising crust",
    category: "Frozen Foods",
    price: 4.98,
    unit: "each",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0013",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Frozen Pizza",
    brand: "Store Brand",
    size: "rising crust",
    category: "Frozen Foods",
    price: 5.49,
    unit: "each",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0014",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Frozen Mixed Vegetables",
    brand: "Great Value",
    size: "12 oz",
    category: "Frozen Foods",
    price: 1.16,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0014",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Frozen Mixed Vegetables",
    brand: "Store Brand",
    size: "12 oz",
    category: "Frozen Foods",
    price: 1.39,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0015",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Frozen Broccoli",
    brand: "Great Value",
    size: "12 oz",
    category: "Frozen Foods",
    price: 1.16,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0015",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Frozen Broccoli",
    brand: "Store Brand",
    size: "12 oz",
    category: "Frozen Foods",
    price: 1.39,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0016",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "White Rice",
    brand: "Great Value",
    size: "5 lb",
    category: "Dry Goods",
    price: 3.34,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0016",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "White Rice",
    brand: "Store Brand",
    size: "5 lb",
    category: "Dry Goods",
    price: 3.69,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0017",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Pinto Beans",
    brand: "Great Value",
    size: "4 lb dry",
    category: "Dry Goods",
    price: 3.98,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0017",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Pinto Beans",
    brand: "Store Brand",
    size: "4 lb dry",
    category: "Dry Goods",
    price: 4.39,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0018",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Black Beans",
    brand: "Great Value",
    size: "15 oz can",
    category: "Canned Goods",
    price: 0.86,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0018",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Black Beans",
    brand: "Store Brand",
    size: "15 oz can",
    category: "Canned Goods",
    price: 0.99,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0019",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Pinto Beans Canned",
    brand: "Great Value",
    size: "15 oz can",
    category: "Canned Goods",
    price: 0.86,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0019",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Pinto Beans Canned",
    brand: "Store Brand",
    size: "15 oz can",
    category: "Canned Goods",
    price: 0.99,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0020",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Canned Corn",
    brand: "Great Value",
    size: "15 oz can",
    category: "Canned Goods",
    price: 0.78,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0020",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Canned Corn",
    brand: "Store Brand",
    size: "15 oz can",
    category: "Canned Goods",
    price: 0.89,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0021",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Green Beans",
    brand: "Great Value",
    size: "14.5 oz can",
    category: "Canned Goods",
    price: 0.78,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0021",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Green Beans",
    brand: "Store Brand",
    size: "14.5 oz can",
    category: "Canned Goods",
    price: 0.89,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0022",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Diced Tomatoes",
    brand: "Great Value",
    size: "14.5 oz can",
    category: "Canned Goods",
    price: 0.96,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0022",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Diced Tomatoes",
    brand: "Store Brand",
    size: "14.5 oz can",
    category: "Canned Goods",
    price: 1.09,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0023",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Tomato Sauce",
    brand: "Great Value",
    size: "8 oz can",
    category: "Canned Goods",
    price: 0.52,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0023",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Tomato Sauce",
    brand: "Store Brand",
    size: "8 oz can",
    category: "Canned Goods",
    price: 0.65,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0024",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Chicken Broth",
    brand: "Great Value",
    size: "32 oz",
    category: "Canned Goods",
    price: 1.38,
    unit: "carton",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0024",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Chicken Broth",
    brand: "Store Brand",
    size: "32 oz",
    category: "Canned Goods",
    price: 1.59,
    unit: "carton",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0025",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Spaghetti Noodles",
    brand: "Great Value",
    size: "16 oz",
    category: "Dry Goods",
    price: 0.98,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0025",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Spaghetti Noodles",
    brand: "Store Brand",
    size: "16 oz",
    category: "Dry Goods",
    price: 1.19,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0026",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Macaroni and Cheese",
    brand: "Great Value",
    size: "7.25 oz",
    category: "Dry Goods",
    price: 0.58,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0026",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Macaroni and Cheese",
    brand: "Store Brand",
    size: "7.25 oz",
    category: "Dry Goods",
    price: 0.69,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0027",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Flour",
    brand: "Great Value",
    size: "5 lb",
    category: "Baking Goods",
    price: 2.43,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0027",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Flour",
    brand: "Store Brand",
    size: "5 lb",
    category: "Baking Goods",
    price: 2.69,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0028",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Sugar",
    brand: "Great Value",
    size: "4 lb",
    category: "Baking Goods",
    price: 3.12,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0028",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Sugar",
    brand: "Store Brand",
    size: "4 lb",
    category: "Baking Goods",
    price: 3.39,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0029",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Brown Sugar",
    brand: "Great Value",
    size: "2 lb",
    category: "Baking Goods",
    price: 2.24,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0029",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Brown Sugar",
    brand: "Store Brand",
    size: "2 lb",
    category: "Baking Goods",
    price: 2.49,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0030",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Baking Powder",
    brand: "Great Value",
    size: "8.1 oz",
    category: "Baking Goods",
    price: 1.72,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0030",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Baking Powder",
    brand: "Store Brand",
    size: "8.1 oz",
    category: "Baking Goods",
    price: 1.99,
    unit: "can",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0031",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Vanilla Extract",
    brand: "Great Value",
    size: "2 fl oz",
    category: "Baking Goods",
    price: 4.98,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0031",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Vanilla Extract",
    brand: "Store Brand",
    size: "2 fl oz",
    category: "Baking Goods",
    price: 5.49,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0032",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Salt",
    brand: "Great Value",
    size: "26 oz",
    category: "Spices",
    price: 0.76,
    unit: "container",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0032",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Salt",
    brand: "Store Brand",
    size: "26 oz",
    category: "Spices",
    price: 0.89,
    unit: "container",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0033",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Black Pepper",
    brand: "Great Value",
    size: "3 oz",
    category: "Spices",
    price: 2.98,
    unit: "container",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0033",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Black Pepper",
    brand: "Store Brand",
    size: "3 oz",
    category: "Spices",
    price: 3.29,
    unit: "container",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0034",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Garlic Powder",
    brand: "Great Value",
    size: "3.4 oz",
    category: "Spices",
    price: 2.24,
    unit: "container",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0034",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Garlic Powder",
    brand: "Store Brand",
    size: "3.4 oz",
    category: "Spices",
    price: 2.49,
    unit: "container",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0035",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Onion Powder",
    brand: "Great Value",
    size: "3.25 oz",
    category: "Spices",
    price: 2.24,
    unit: "container",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0035",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Onion Powder",
    brand: "Store Brand",
    size: "3.25 oz",
    category: "Spices",
    price: 2.49,
    unit: "container",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0036",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Taco Seasoning",
    brand: "Great Value",
    size: "1 oz packet",
    category: "Spices",
    price: 0.48,
    unit: "packet",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0036",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Taco Seasoning",
    brand: "Store Brand",
    size: "1 oz packet",
    category: "Spices",
    price: 0.59,
    unit: "packet",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0037",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Ketchup",
    brand: "Great Value",
    size: "32 oz",
    category: "Sauces",
    price: 1.98,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0037",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Ketchup",
    brand: "Store Brand",
    size: "32 oz",
    category: "Sauces",
    price: 2.29,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0038",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Mustard",
    brand: "Great Value",
    size: "20 oz",
    category: "Sauces",
    price: 1.24,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0038",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Mustard",
    brand: "Store Brand",
    size: "20 oz",
    category: "Sauces",
    price: 1.49,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0039",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Mayonnaise",
    brand: "Great Value",
    size: "30 oz",
    category: "Sauces",
    price: 3.98,
    unit: "jar",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0039",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Mayonnaise",
    brand: "Store Brand",
    size: "30 oz",
    category: "Sauces",
    price: 4.39,
    unit: "jar",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0040",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "BBQ Sauce",
    brand: "Great Value",
    size: "18 oz",
    category: "Sauces",
    price: 1.48,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0040",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "BBQ Sauce",
    brand: "Store Brand",
    size: "18 oz",
    category: "Sauces",
    price: 1.79,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0041",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Ranch Dressing",
    brand: "Great Value",
    size: "16 oz",
    category: "Sauces",
    price: 2.24,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0041",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Ranch Dressing",
    brand: "Store Brand",
    size: "16 oz",
    category: "Sauces",
    price: 2.49,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0042",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Salsa",
    brand: "Great Value",
    size: "24 oz",
    category: "Sauces",
    price: 2.48,
    unit: "jar",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0042",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Salsa",
    brand: "Store Brand",
    size: "24 oz",
    category: "Sauces",
    price: 2.79,
    unit: "jar",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0043",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Loaf Bread",
    brand: "Great Value",
    size: "20 oz",
    category: "Dry Goods",
    price: 1.42,
    unit: "loaf",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0043",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Loaf Bread",
    brand: "Store Brand",
    size: "20 oz",
    category: "Dry Goods",
    price: 1.79,
    unit: "loaf",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0044",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Flour Tortillas",
    brand: "Great Value",
    size: "10 count",
    category: "Dry Goods",
    price: 1.98,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0044",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Flour Tortillas",
    brand: "Store Brand",
    size: "10 count",
    category: "Dry Goods",
    price: 2.29,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0045",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Corn Tortillas",
    brand: "Great Value",
    size: "30 count",
    category: "Dry Goods",
    price: 1.98,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0045",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Corn Tortillas",
    brand: "Store Brand",
    size: "30 count",
    category: "Dry Goods",
    price: 2.29,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0046",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Oatmeal",
    brand: "Great Value",
    size: "42 oz",
    category: "Breakfast",
    price: 3.98,
    unit: "canister",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0046",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Oatmeal",
    brand: "Store Brand",
    size: "42 oz",
    category: "Breakfast",
    price: 4.39,
    unit: "canister",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0047",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Cereal",
    brand: "Great Value",
    size: "family size",
    category: "Breakfast",
    price: 3.98,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0047",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Cereal",
    brand: "Store Brand",
    size: "family size",
    category: "Breakfast",
    price: 4.49,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0048",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Pancake Mix",
    brand: "Great Value",
    size: "32 oz",
    category: "Breakfast",
    price: 2.68,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0048",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Pancake Mix",
    brand: "Store Brand",
    size: "32 oz",
    category: "Breakfast",
    price: 2.99,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0049",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Syrup",
    brand: "Great Value",
    size: "24 fl oz",
    category: "Breakfast",
    price: 2.24,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0049",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Syrup",
    brand: "Store Brand",
    size: "24 fl oz",
    category: "Breakfast",
    price: 2.49,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0050",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Bananas",
    brand: "Produce",
    size: "per lb",
    category: "Fruits",
    price: 0.58,
    unit: "lb",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0050",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Bananas",
    brand: "Produce",
    size: "per lb",
    category: "Fruits",
    price: 0.69,
    unit: "lb",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0051",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Apples",
    brand: "Produce",
    size: "3 lb bag",
    category: "Fruits",
    price: 4.98,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0051",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Apples",
    brand: "Produce",
    size: "3 lb bag",
    category: "Fruits",
    price: 5.49,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0052",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Oranges",
    brand: "Produce",
    size: "3 lb bag",
    category: "Fruits",
    price: 4.98,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0052",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Oranges",
    brand: "Produce",
    size: "3 lb bag",
    category: "Fruits",
    price: 5.49,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0053",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Strawberries",
    brand: "Produce",
    size: "1 lb",
    category: "Fruits",
    price: 3.48,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0053",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Strawberries",
    brand: "Produce",
    size: "1 lb",
    category: "Fruits",
    price: 3.99,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0054",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Potatoes",
    brand: "Produce",
    size: "5 lb bag",
    category: "Vegetables",
    price: 3.48,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0054",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Potatoes",
    brand: "Produce",
    size: "5 lb bag",
    category: "Vegetables",
    price: 3.99,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0055",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Onions",
    brand: "Produce",
    size: "3 lb bag",
    category: "Vegetables",
    price: 2.98,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0055",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Onions",
    brand: "Produce",
    size: "3 lb bag",
    category: "Vegetables",
    price: 3.29,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0056",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Carrots",
    brand: "Produce",
    size: "2 lb bag",
    category: "Vegetables",
    price: 1.96,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0056",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Carrots",
    brand: "Produce",
    size: "2 lb bag",
    category: "Vegetables",
    price: 2.19,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0057",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Lettuce",
    brand: "Produce",
    size: "1 head",
    category: "Vegetables",
    price: 1.98,
    unit: "each",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0057",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Lettuce",
    brand: "Produce",
    size: "1 head",
    category: "Vegetables",
    price: 2.29,
    unit: "each",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0058",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Tomatoes",
    brand: "Produce",
    size: "per lb",
    category: "Vegetables",
    price: 1.98,
    unit: "lb",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0058",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Tomatoes",
    brand: "Produce",
    size: "per lb",
    category: "Vegetables",
    price: 2.29,
    unit: "lb",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0059",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Bell Peppers",
    brand: "Produce",
    size: "3 count",
    category: "Vegetables",
    price: 3.48,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0059",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Bell Peppers",
    brand: "Produce",
    size: "3 count",
    category: "Vegetables",
    price: 3.99,
    unit: "pkg",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0060",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Coffee",
    brand: "Great Value",
    size: "30.5 oz",
    category: "Drinks",
    price: 8.98,
    unit: "canister",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0060",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Coffee",
    brand: "Store Brand",
    size: "30.5 oz",
    category: "Drinks",
    price: 9.49,
    unit: "canister",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0061",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Bottled Water",
    brand: "Great Value",
    size: "40 pack",
    category: "Drinks",
    price: 5.36,
    unit: "case",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0061",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Bottled Water",
    brand: "Store Brand",
    size: "40 pack",
    category: "Drinks",
    price: 5.99,
    unit: "case",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0062",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Orange Juice",
    brand: "Great Value",
    size: "52 fl oz",
    category: "Drinks",
    price: 3.18,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0062",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Orange Juice",
    brand: "Store Brand",
    size: "52 fl oz",
    category: "Drinks",
    price: 3.49,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0063",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Apple Juice",
    brand: "Great Value",
    size: "64 fl oz",
    category: "Drinks",
    price: 2.44,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0063",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Apple Juice",
    brand: "Store Brand",
    size: "64 fl oz",
    category: "Drinks",
    price: 2.79,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0064",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Chips",
    brand: "Great Value",
    size: "13 oz",
    category: "Snacks",
    price: 2.48,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0064",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Chips",
    brand: "Store Brand",
    size: "13 oz",
    category: "Snacks",
    price: 2.79,
    unit: "bag",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0065",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Crackers",
    brand: "Great Value",
    size: "13.7 oz",
    category: "Snacks",
    price: 2.28,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0065",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Crackers",
    brand: "Store Brand",
    size: "13.7 oz",
    category: "Snacks",
    price: 2.59,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0066",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Peanut Butter",
    brand: "Great Value",
    size: "40 oz",
    category: "Dry Goods",
    price: 4.48,
    unit: "jar",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0066",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Peanut Butter",
    brand: "Store Brand",
    size: "40 oz",
    category: "Dry Goods",
    price: 4.89,
    unit: "jar",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0067",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Jelly",
    brand: "Great Value",
    size: "30 oz",
    category: "Dry Goods",
    price: 2.74,
    unit: "jar",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0067",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Jelly",
    brand: "Store Brand",
    size: "30 oz",
    category: "Dry Goods",
    price: 2.99,
    unit: "jar",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0068",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Paper Towels",
    brand: "Great Value",
    size: "6 double rolls",
    category: "Household",
    price: 9.98,
    unit: "pack",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0068",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Paper Towels",
    brand: "Store Brand",
    size: "6 double rolls",
    category: "Household",
    price: 10.99,
    unit: "pack",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0069",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Toilet Paper",
    brand: "Great Value",
    size: "12 mega rolls",
    category: "Household",
    price: 12.98,
    unit: "pack",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0069",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Toilet Paper",
    brand: "Store Brand",
    size: "12 mega rolls",
    category: "Household",
    price: 13.99,
    unit: "pack",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0070",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Trash Bags",
    brand: "Great Value",
    size: "80 count",
    category: "Household",
    price: 11.97,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0070",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Trash Bags",
    brand: "Store Brand",
    size: "80 count",
    category: "Household",
    price: 12.99,
    unit: "box",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0071",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Dish Soap",
    brand: "Great Value",
    size: "38 fl oz",
    category: "Household",
    price: 3.24,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0071",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Dish Soap",
    brand: "Store Brand",
    size: "38 fl oz",
    category: "Household",
    price: 3.59,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-wm-0072",
    store: "Walmart",
    storeName: "Walmart Supercenter #793",
    storeZip: "79015",
    zipCode: "79015",
    name: "Laundry Detergent",
    brand: "Great Value",
    size: "100 fl oz",
    category: "Household",
    price: 8.47,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  },
  {
    id: "seed-united-0072",
    store: "United Supermarkets",
    storeName: "United Supermarkets N 23rd & Russell Long",
    storeZip: "79015",
    zipCode: "79015",
    name: "Laundry Detergent",
    brand: "Store Brand",
    size: "100 fl oz",
    category: "Household",
    price: 8.99,
    unit: "bottle",
    lastChecked: "2026-06-15",
    notes: "Starter planning price; verify before shopping."
  }
];


export const DEFAULT_DATA: AppData = {
  users: [
    { id: 'user-owner', name: 'Owner', role: 'owner' },
    { id: 'user-household', name: 'Household Member', role: 'household_member' }
  ],
  currentUserId: 'user-owner',
  accounts: [
    { id: 'acct-checking', name: 'Checking', type: 'checking', startingBalance: 0 }
  ],
  transactions: [],
  budgetCategories: [
    { id: 'cat-grocery', name: 'Groceries', monthlyBudget: 800 },
    { id: 'cat-household', name: 'Household', monthlyBudget: 150 },
    { id: 'cat-utilities', name: 'Utilities', monthlyBudget: 600 }
  ],
  debts: [],
  shoppingLists: [
    {
      id: 'list-grocery',
      name: 'Main Grocery List',
      type: 'grocery',
      sharedWith: ['user-owner', 'user-household'],
      items: []
    }
  ],
  priceCatalog: DEFAULT_PRICE_CATALOG,
  statementImports: [],
  pantryItems: [
    { id: 'pantry-rice', name: 'White Rice', category: 'Dry Goods', quantity: 5, unit: 'lb', location: 'Pantry', estimatedUnitPrice: 0.98, lastUpdated: '2026-06-12' },
    { id: 'pantry-salt', name: 'Salt', category: 'Spices', quantity: 1, unit: 'container', location: 'Spice Cabinet', estimatedUnitPrice: 1.24, lastUpdated: '2026-06-12' },
    { id: 'pantry-chicken', name: 'Frozen Chicken Breast', category: 'Meats', quantity: 2, unit: 'lb', location: 'Freezer', estimatedUnitPrice: 3.25, lastUpdated: '2026-06-12' }
  ],
  recipes: [
    {
      id: 'recipe-chicken-tacos',
      name: 'Chicken Tacos',
      servings: 5,
      category: 'Dinner',
      source: 'starter',
      createdAt: '2026-06-15T00:00:00.000Z',
      updatedAt: '2026-06-15T00:00:00.000Z',
      notes: 'Starter recipe to show pantry and meal planner matching.',
      instructions: 'Cook chicken, season, warm tortillas, and top with cheese and sour cream.',
      ingredients: [
        { id: 'recipe-chicken-tacos-ing-1', name: 'Chicken Breast', quantity: 2, unit: 'lb', category: 'Meats', estimatedPrice: 7.50, pantryCovered: false },
        { id: 'recipe-chicken-tacos-ing-2', name: 'Tortillas', quantity: 1, unit: 'package', category: 'Dry Goods', estimatedPrice: 2.48, pantryCovered: false },
        { id: 'recipe-chicken-tacos-ing-3', name: 'Shredded Cheddar Cheese', quantity: 1, unit: 'bag', category: 'Dairy', estimatedPrice: 3.98, pantryCovered: false },
        { id: 'recipe-chicken-tacos-ing-4', name: 'Sour Cream', quantity: 1, unit: 'tub', category: 'Dairy', estimatedPrice: 1.98, pantryCovered: false }
      ]
    }
  ],
  mealPlans: []
};

function catalogKey(item: PriceCatalogItem): string {
  return [item.store, item.name, item.brand ?? '', item.size ?? ''].map((part) => String(part).trim().toLowerCase()).join('|');
}

export function mergeDefaultPriceCatalog(existing: PriceCatalogItem[] | undefined | null): PriceCatalogItem[] {
  const merged: PriceCatalogItem[] = [];
  const seen = new Set<string>();
  for (const item of [...(existing ?? []), ...DEFAULT_PRICE_CATALOG]) {
    const key = catalogKey(item);
    if (seen.has(key)) continue;
    seen.add(key);
    merged.push(item);
  }
  return merged.sort((a, b) => a.store.localeCompare(b.store) || (a.category ?? '').localeCompare(b.category ?? '') || a.name.localeCompare(b.name));
}

function parseStoredData(key: string): Partial<AppData> | null {
  const raw = localStorage.getItem(key);
  if (!raw) return null;
  try {
    return JSON.parse(raw) as Partial<AppData>;
  } catch (error) {
    console.warn(`Unable to parse HomeLife storage key ${key}`, error);
    return null;
  }
}

export function loadData(): Partial<AppData> | null {
  if (typeof localStorage === 'undefined') return DEFAULT_DATA;
  const keys = [STORAGE_KEY, ...LEGACY_KEYS];
  const parsed = keys.map(parseStoredData).filter((item): item is Partial<AppData> => Boolean(item));
  if (!parsed.length) return DEFAULT_DATA;

  const primary = parsed[0];
  const legacyPriceCatalog = parsed.flatMap((item) => item.priceCatalog ?? []);
  const shouldRestoreCatalog = legacyPriceCatalog.length < DEFAULT_PRICE_CATALOG.length;
  if (shouldRestoreCatalog) {
    const repaired = {
      ...primary,
      priceCatalog: mergeDefaultPriceCatalog(legacyPriceCatalog)
    };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(repaired));
    localStorage.setItem(CATALOG_RESTORE_FLAG, 'true');
    return repaired;
  }

  if ((primary.priceCatalog ?? []).length === 0 && legacyPriceCatalog.length > 0) {
    return { ...primary, priceCatalog: mergeDefaultPriceCatalog(legacyPriceCatalog) };
  }
  return primary;
}

export function saveData(data: AppData): void {
  if (typeof localStorage === 'undefined') return;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
}

export function resetData(): void {
  if (typeof localStorage === 'undefined') return;
  [STORAGE_KEY, ...LEGACY_KEYS, CATALOG_RESTORE_FLAG].forEach((key) => localStorage.removeItem(key));
}
